Django_Project/food/config/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main_recipe/', include('main_recipe.urls')),
    path('share_recipe/', include('share_recipe.urls')),
    path('best_recipe/', include('food.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('', views.mainpage, name = 'main'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django_Project/food/food/urls.py
from django.contrib import admin
from django.urls import path
from share_recipe.views import recipe_list_views

app_name = 'best'

urlpatterns = [
    path('', recipe_list_views.best_recipe_list, name = 'index'),
]

Django_Project/food/main_recipe/urls.py
from django.contrib import admin
from django.urls import path
from .views import base_views, recipe_list_views, recipe_views


app_name = 'main'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('korean/', recipe_list_views.korean, name = 'korean'),
    path('chinese/', recipe_list_views.chinese, name = 'chinese'),
    path('western/', recipe_list_views.western, name = 'western'),
    path('japanese/', recipe_list_views.japanese, name = 'japanese'),
    path('<int:recipe_id>/', base_views.recipe_detail, name = 'recipe_detail'),
    path('recipe/create/', recipe_views.recipe_create, name='recipe_create'),
    path('recipe/modify/<int:recipe_id>/', recipe_views.recipe_modify, name = 'recipe_modify'),
    path('recipe/delete/<int:recipe_id>/', recipe_views.recipe_delete, name = 'recipe_delete'),
]

Django_Project/food/food/models.py
from django.contrib.auth.models import User
from django.db import models


menu_Korea = "한식"
menu_China = "중식"
menu_Western = "양식"
menu_Japan = "일식"
menu_Choice = ((menu_Korea, "한식"), (menu_China, "중식"), (menu_Western, "양식"), (menu_Japan, "일식"))

class share_recipe(models.Model):
    subject = models.CharField(max_length=200)
    menu = models.CharField(choices=menu_Choice, max_length = 10)
    material = models.TextField()
    how_Make = models.TextField()
    create_date = models.DateTimeField()


    def __str__(self):
        return self.subject

class Answer(models.Model):
    recipe = models.ForeignKey(share_recipe, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

Django_Project/food/main_recipe/models.py
from django.contrib.auth.models import User
from django.db import models

menu_Korea = "한식"
menu_China = "중식"
menu_Western = "양식"
menu_Japan = "일식"
menu_Choice = ((menu_Korea, "한식"), (menu_China, "중식"), (menu_Western, "양식"), (menu_Japan, "일식"))


class main_recipe(models.Model):
    subject = models.CharField(max_length=200)
    menu = models.CharField(choices=menu_Choice, max_length=10)
    material = models.TextField()
    how_Make = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Photo(models.Model):
    recipe = models.ForeignKey(main_recipe, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

Django_Project/food/main_recipe/views/recipe_views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from ..models import main_recipe, Photo
from ..forms import RecipeForm


@login_required(login_url = "common:login")
def recipe_create(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.create_date = timezone.now()
            recipe.save()
            for img in request.FILES.getlist('imgs'):
                photo = Photo()
                photo.recipe = recipe
                photo.image = img
                photo.save()

            if recipe.menu == "한식":
                return redirect('main:korean')
            elif recipe.menu == "중식":
                return redirect('main:chinese')
            elif recipe.menu == "일식":
                return redirect('main:japanese')
            else:
                return redirect('main:western')
    else:
        form = RecipeForm()
    context = {'form' : form}
    return render(request, 'main/recipe_form.html', context)


@login_required(login_url = "common:login")
def recipe_modify(request, recipe_id):
    recipe = get_object_or_404(main_recipe, pk=recipe_id)
    if request.user != recipe.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('main:recipe_detail', recipe_id = recipe.id)

    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.modify_date = timezone.now()
            recipe.save()
            for img in request.FILES.getlist('imgs'):
                photo = Photo()
                photo.recipe = recipe
                photo.image = img
                photo.save()
            return redirect('main:recipe_detail', recipe_id = recipe.id)
    else:
        form = RecipeForm(instance=recipe)
    context = {'form': form}
    return render(request, 'main/recipe_form.html', context)


@login_required(login_url = "common:login")
def recipe_delete(request, recipe_id):
    recipe = get_object_or_404(main_recipe, pk=recipe_id)
    if request.user != recipe.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('main:recipe_detail', recipe_id = recipe.id)
    recipe.delete()
    return redirect('main:index')

Django_Project/food/share_recipe/views/recipe_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.utils import timezone
from ..forms import RecipeForm
from ..models import share_recipe, Photo


@login_required(login_url = "common:login")
def recipe_create(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.create_date = timezone.now()
            recipe.save()
            for img in request.FILES.getlist('imgs'):
                photo = Photo()
                photo.recipe = recipe
                photo.image = img
                photo.save()

            if recipe.menu == "한식":
                return redirect('share:korean')
            elif recipe.menu == "중식":
                return redirect('share:chinese')
            elif recipe.menu == "일식":
                return redirect('share:japanese')
            else:
                return redirect('share:western')
    else:
        form = RecipeForm()
    context = {'form' : form}
    return render(request, 'share/recipe_form.html', context)


@login_required(login_url = "common:login")
def recipe_modify(request, recipe_id):
    recipe = get_object_or_404(share_recipe, pk=recipe_id)
    if request.user != recipe.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('share:recipe_detail', recipe_id = recipe.id)

    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.modify_date = timezone.now()
            recipe.save()
            for img in request.FILES.getlist('imgs'):
                photo = Photo()
                photo.recipe = recipe
                photo.image = img
                photo.save()
            return redirect('share:recipe_detail', recipe_id = recipe.id)
    else:
        form = RecipeForm(instance=recipe)
    context = {'form': form}
    return render(request, 'share/recipe_form.html', context)


@login_required(login_url = "common:login")
def recipe_delete(request, recipe_id):
    recipe = get_object_or_404(share_recipe, pk=recipe_id)
    if request.user != recipe.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('share:recipe_detail', recipe_id = recipe.id)
    recipe.delete()
    return redirect('share:index')

Django_Project/food/templates/main/chinese_recipe_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <h2 class="banner">메인레시피 - 중식<br></h2>
    <h3 class="sub" style="font-size:20px;"> * 검증된 중식 음식입니다.</h3>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style = "width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if recipe_list %}
        {% for recipe in recipe_list %}
        <tr class = "text-center">
            <td>{{ recipe_list.paginator.count|sub:recipe_list.start_index|sub:forloop.counter0|add:1 }}</td> <!--forloop.counter-->
            <td class = "text-left">
                <a href="{% url 'main:recipe_detail' recipe.id %}">
                    {{ recipe.subject }}
                    {% if recipe.answer_set.count > 0 %}
                    <span class = "text-danger small ml-2">
                        {{ recipe.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
            </td>
            <td>{{ recipe.author.username }}</td>
            <td>{{ recipe.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">레시피가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if recipe_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in recipe_list.paginator.page_range %}
        {% if page_number >= recipe_list.number|add:-5 and page_number <= recipe_list.number|add:5 %}
            {% if page_number == recipe_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if recipe_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>

{% endblock %}

Django_Project/food/templates/main/japanese_recipe_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <h2 class="banner">메인레시피 - 일식<br></h2>
    <h3 class="sub" style="font-size:20px;"> * 검증된 일식 음식입니다.</h3>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style = "width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if recipe_list %}
        {% for recipe in recipe_list %}
        <tr class = "text-center">
            <td>{{ recipe_list.paginator.count|sub:recipe_list.start_index|sub:forloop.counter0|add:1 }}</td> <!--forloop.counter-->
            <td class = "text-left">
                <a href="{% url 'main:recipe_detail' recipe.id %}">
                    {{ recipe.subject }}
                    {% if recipe.answer_set.count > 0 %}
                    <span class = "text-danger small ml-2">
                        {{ recipe.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
            </td>
            <td>{{ recipe.author.username }}</td>
            <td>{{ recipe.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">레시피가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if recipe_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in recipe_list.paginator.page_range %}
        {% if page_number >= recipe_list.number|add:-5 and page_number <= recipe_list.number|add:5 %}
            {% if page_number == recipe_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if recipe_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>

{% endblock %}

Django_Project/food/templates/main/korean_recipe_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <h2 class="banner">메인레시피 - 한식<br></h2>
    <h3 class="sub" style="font-size:20px;"> * 검증된 한국 음식입니다.</h3>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style = "width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if recipe_list %}
        {% for recipe in recipe_list %}
        <tr class = "text-center">
            <td>{{ recipe_list.paginator.count|sub:recipe_list.start_index|sub:forloop.counter0|add:1 }}</td> <!--forloop.counter-->
            <td class = "text-left">
                <a href="{% url 'main:recipe_detail' recipe.id %}">
                    {{ recipe.subject }}
                    {% if recipe.answer_set.count > 0 %}
                    <span class = "text-danger small ml-2">
                        {{ recipe.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
            </td>
            <td>{{ recipe.author.username }}</td>
            <td>{{ recipe.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">레시피가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if recipe_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in recipe_list.paginator.page_range %}
        {% if page_number >= recipe_list.number|add:-5 and page_number <= recipe_list.number|add:5 %}
            {% if page_number == recipe_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if recipe_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>

{% endblock %}

Django_Project/food/templates/main/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--로고-->
<div id="inback">
    <div id="main-in">
        <h2 style="font-size:35pt;"><b>기본적인 레시피가 있는 게시판입니다.</b></h2>
</div>
<div id="inlogo">
        <img src="https://postfiles.pstatic.net/MjAyMTA1MjRfMTIy/MDAxNjIxODQxNzAyNzEz.sw9sfN3XrDFQHtyj3MUqDTx9qkazwoMCM-KuASIBPxgg.Aau2GOTPkBXbKE8df2fVzuEbu29utUVHgFctyzf97e4g.PNG.mmy0509/logo_transparent.png?type=w773"
        style="margin:0 auto; width:300px;">
        <link rel="stylesheet" href="{%static 'style.css'%}?a">
</div>
    <div id="centerfont">
        <img src="https://postfiles.pstatic.net/MjAyMTA1MzBfODIg/MDAxNjIyMzg2NDg1NTky.1xDo0sZl4jPS2UdJHcavF-zqsq8Zj1ywXXqDbPoKWbkg.ISQQTgK_dm0ETdPSs5a3KxEPsh6NnH4PDEJRc9OIBxog.PNG.mmy0509/main.PNG?type=w773">
    </div>
    <!-- 한식 이동 -->
    <div id="korean">
        <a href="{% url 'main:korean' %}" title="전통 한식을 위한 게시판 레시피입니다.">✔한식</a><br>
        <a href="{% url 'main:korean' %}">우리나라 전통의 한식의 조리법을  공유하는 게시판 입니다.</a>
    </div>

    <!-- 중식 이동 -->
    <div id="chinese">
        <a href="{% url 'main:chinese' %}"title="중국 음식을 위한 레시피 게시판 입니다.">✔중식</a><br>
        <a href="{% url 'main:chinese' %}">중국의 조리법을 공유하는 게시판 입니다.</a>
    </div>

    <!-- 양식 이동 -->
    <div id="western">
        <a href="{% url 'main:western' %}"title="서양 음식을 위한 레시피 게시판 입니다">✔양식</a><br>
        <a href="{% url 'main:western' %}">서양의 음식 즉 양식의 조리법을 공유하는 게시판 입니다.  </a>
    </div>

    <!-- 일식 이동 -->
    <div id="japanese">
        <a href="{% url 'main:japanese' %}"title="일본 음식을 위한 레시피 게시판 입니다">✔일식</a><br>
        <a href="{% url 'main:japanese' %}"> 일본의 음식 조리법을 공유하는 게시판 입니다.</a>
    </div>
{% if user.is_authenticated %}
<div id="button">
<a href = "{% url 'main:recipe_create' %}" class = "btn btn-primary">
    레시피 등록하기
</a>
</div>
</div>
{% endif %}
{% endblock %}

Django_Project/food/templates/main/recipe_detail.html
{% extends 'base.html' %}
{% load share_filter %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">메인 레시피 - {{ recipe.subject }}</h2>
    <div class="card my-3">
        {% for photo in recipe.photo_set.all %}
        <img src="{{photo.image.url}}"><br>
        {% endfor %}
        <div class="card-body">
            <div class="card-text">{{ recipe.subject|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if recipe.modify_date %}
                <div class = "badge badge-light p-2 text-left mx-3">
                    <div class = "mb-2">수정 일자</div>
                    <div>{{ recipe.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class = "mb-2">{{ recipe.author.username }}</div>
                    <div>{{ recipe.create_date }}</div>
                </div>
            </div>
            {% if request.user == recipe.author %}
            <div class = "my-3">
                <a href = "{% url 'main:recipe_modify' recipe.id %}" class = "btn btn-sm btn-outline-secondary">수정</a>
                <a href = "#" class = "delete btn btn-sm btn-outline-secondary" data-uri = "{% url 'main:recipe_delete' recipe.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">종류 : {{ recipe.menu }}</div>
        </div>
    </div>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">주재료 : {{ recipe.material|mark }}</div>
        </div>
    </div>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">만드는 법 : {{ recipe.how_Make|mark }}</div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type = 'text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

Django_Project/food/templates/main/recipe_form.html
{% extends 'base.html' %}

{% block content %}
<div class = "container">
    <h5 class = "my-3 border-bottom pb-2">레시피 등록</h5>
    <form method = "post" class = "post-form my-3" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="form-group">
                <label for="subject">레시피 이름</label>
                <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label>종류</label>
                {{ form.menu }}
            </div>
            <div class="form-group">
                <label for="material">재료</label>
                    <textarea class="form-control" name="material" id="material" rows="5">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <div class="form-group">
                <label for="how_Make">만드는 법</label>
                    <textarea class="form-control" name="how_Make" id="how_Make" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <div class="form-group">
                <input type = "file" name="imgs" multiple>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

Django_Project/food/templates/main/western_recipe_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <h2 class="banner">메인레시피 - 양식<br></h2>
    <h3 class="sub" style="font-size:20px;"> * 검증된 양식 음식입니다.</h3>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style = "width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if recipe_list %}
        {% for recipe in recipe_list %}
        <tr class = "text-center">
            <td>{{ recipe_list.paginator.count|sub:recipe_list.start_index|sub:forloop.counter0|add:1 }}</td> <!--forloop.counter-->
            <td class = "text-left">
                <a href="{% url 'main:recipe_detail' recipe.id %}">
                    {{ recipe.subject }}
                    {% if recipe.answer_set.count > 0 %}
                    <span class = "text-danger small ml-2">
                        {{ recipe.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
            </td>
            <td>{{ recipe.author.username }}</td>
            <td>{{ recipe.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">레시피가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if recipe_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in recipe_list.paginator.page_range %}
        {% if page_number >= recipe_list.number|add:-5 and page_number <= recipe_list.number|add:5 %}
            {% if page_number == recipe_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if recipe_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>

{% endblock %}