Django_Project/food/config/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main_recipe/', include('main_recipe.urls')),
    path('share_recipe/', include('share_recipe.urls')),
    path('best_recipe/', include('food.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('', views.mainpage, name = 'main'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django_Project/food/food/urls.py
from django.contrib import admin
from django.urls import path
from share_recipe.views import recipe_list_views

app_name = 'best'

urlpatterns = [
    path('', recipe_list_views.best_recipe_list, name = 'index'),
]

Django_Project/food/share_recipe/urls.py
from django.urls import path
from .views import answer_views, base_views, comment_views, recipe_list_views, recipe_views, voter_views

app_name = 'share'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('korean/', recipe_list_views.korean, name = 'korean'),
    path('chinese/', recipe_list_views.chinese, name = 'chinese'),
    path('western/', recipe_list_views.western, name = 'western'),
    path('japanese/', recipe_list_views.japanese, name = 'japanese'),
    path('<int:recipe_id>/', base_views.recipe_detail, name = 'recipe_detail'),
    path('answer/create/<int:recipe_id>/', answer_views.answer_create, name = 'answer_create'),
    path('recipe/create/', recipe_views.recipe_create, name = 'recipe_create'),
    path('recipe/modify/<int:recipe_id>/', recipe_views.recipe_modify, name = 'recipe_modify'),
    path('recipe/delete/<int:recipe_id>/', recipe_views.recipe_delete, name = 'recipe_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),
    path('comment/create/recipe/<int:recipe_id>/', comment_views.comment_create_recipe, name = 'comment_create_recipe'),
    path('comment/modify/recipe/<int:comment_id>/', comment_views.comment_modify_recipe, name = 'comment_modify_recipe'),
    path('comment/delete/recipe/<int:comment_id>/', comment_views.comment_delete_recipe, name = 'comment_delete_recipe'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:recipe_id>/', voter_views.vote_recipe, name='vote_recipe'),
    path('vote/answer/<int:answer_id>/', voter_views.vote_answer, name='vote_answer'),
]

Django_Project/food/food/models.py
from django.contrib.auth.models import User
from django.db import models


menu_Korea = "한식"
menu_China = "중식"
menu_Western = "양식"
menu_Japan = "일식"
menu_Choice = ((menu_Korea, "한식"), (menu_China, "중식"), (menu_Western, "양식"), (menu_Japan, "일식"))

class share_recipe(models.Model):
    subject = models.CharField(max_length=200)
    menu = models.CharField(choices=menu_Choice, max_length = 10)
    material = models.TextField()
    how_Make = models.TextField()
    create_date = models.DateTimeField()


    def __str__(self):
        return self.subject

class Answer(models.Model):
    recipe = models.ForeignKey(share_recipe, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

Django_Project/food/templates/best/best_recipe_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <h2 class="banner">추천 레시피<br></h2>
    <h3 class="sub" style="font-size:20px;"> * 오늘의 추천 레시피 입니다. 본인 외 사람이 추천한 레시피 입니다.</h3>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>추천</th>
            <th style = "width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if recipe_list %}
        {% for recipe in recipe_list %}
               <tr class = "text-center">
            <td>{{ recipe_list.paginator.count|sub:recipe_list.start_index|sub:forloop.counter0|add:1 }}</td> <!--forloop.counter-->
            <td>
            {% if recipe.voter.all.count > 0 %}
            <span class="badge badge-warning px-2 py-1">{{ recipe.voter.all.count }}</span>
            {% endif %}
            </td>
            </td>
            <td class = "text-left">
                <a href="{% url 'share:recipe_detail' recipe.id %}">
                    {{ recipe.subject }}
                    {% if recipe.answer_set.count > 0 %}
                    <span class = "text-danger small ml-2">
                        {{ recipe.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
            </td>
            <td>{{ recipe.author.username }}</td>
            <td>{{ recipe.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">레시피가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if recipe_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in recipe_list.paginator.page_range %}
        {% if page_number >= recipe_list.number|add:-5 and page_number <= recipe_list.number|add:5 %}
            {% if page_number == recipe_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if recipe_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ recipe_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>

{% endblock %}