Django_Project/food/config/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main_recipe/', include('main_recipe.urls')),
    path('share_recipe/', include('share_recipe.urls')),
    path('best_recipe/', include('food.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('', views.mainpage, name = 'main'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django_Project/food/food/urls.py
from django.contrib import admin
from django.urls import path
from share_recipe.views import recipe_list_views

app_name = 'best'

urlpatterns = [
    path('', recipe_list_views.best_recipe_list, name = 'index'),
]

Django_Project/food/share_recipe/urls.py
from django.urls import path
from .views import answer_views, base_views, comment_views, recipe_list_views, recipe_views, voter_views

app_name = 'share'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('korean/', recipe_list_views.korean, name = 'korean'),
    path('chinese/', recipe_list_views.chinese, name = 'chinese'),
    path('western/', recipe_list_views.western, name = 'western'),
    path('japanese/', recipe_list_views.japanese, name = 'japanese'),
    path('<int:recipe_id>/', base_views.recipe_detail, name = 'recipe_detail'),
    path('answer/create/<int:recipe_id>/', answer_views.answer_create, name = 'answer_create'),
    path('recipe/create/', recipe_views.recipe_create, name = 'recipe_create'),
    path('recipe/modify/<int:recipe_id>/', recipe_views.recipe_modify, name = 'recipe_modify'),
    path('recipe/delete/<int:recipe_id>/', recipe_views.recipe_delete, name = 'recipe_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),
    path('comment/create/recipe/<int:recipe_id>/', comment_views.comment_create_recipe, name = 'comment_create_recipe'),
    path('comment/modify/recipe/<int:comment_id>/', comment_views.comment_modify_recipe, name = 'comment_modify_recipe'),
    path('comment/delete/recipe/<int:comment_id>/', comment_views.comment_delete_recipe, name = 'comment_delete_recipe'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:recipe_id>/', voter_views.vote_recipe, name='vote_recipe'),
    path('vote/answer/<int:answer_id>/', voter_views.vote_answer, name='vote_answer'),
]

Django_Project/food/food/models.py
from django.contrib.auth.models import User
from django.db import models


menu_Korea = "한식"
menu_China = "중식"
menu_Western = "양식"
menu_Japan = "일식"
menu_Choice = ((menu_Korea, "한식"), (menu_China, "중식"), (menu_Western, "양식"), (menu_Japan, "일식"))

class share_recipe(models.Model):
    subject = models.CharField(max_length=200)
    menu = models.CharField(choices=menu_Choice, max_length = 10)
    material = models.TextField()
    how_Make = models.TextField()
    create_date = models.DateTimeField()


    def __str__(self):
        return self.subject

class Answer(models.Model):
    recipe = models.ForeignKey(share_recipe, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

Django_Project/food/main_recipe/models.py
from django.contrib.auth.models import User
from django.db import models

menu_Korea = "한식"
menu_China = "중식"
menu_Western = "양식"
menu_Japan = "일식"
menu_Choice = ((menu_Korea, "한식"), (menu_China, "중식"), (menu_Western, "양식"), (menu_Japan, "일식"))


class main_recipe(models.Model):
    subject = models.CharField(max_length=200)
    menu = models.CharField(choices=menu_Choice, max_length=10)
    material = models.TextField()
    how_Make = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Photo(models.Model):
    recipe = models.ForeignKey(main_recipe, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

Django_Project/food/share_recipe/models.py
from django.contrib.auth.models import User
from django.db import models


menu_Korea = "한식"
menu_China = "중식"
menu_Western = "양식"
menu_Japan = "일식"
menu_Choice = ((menu_Korea, "한식"), (menu_China, "중식"), (menu_Western, "양식"), (menu_Japan, "일식"))

class share_recipe(models.Model):
    subject = models.CharField(max_length=200)
    menu = models.CharField(choices=menu_Choice, max_length = 10)
    material = models.TextField()
    how_Make = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'author_recipe')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name = 'voter_recipe')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    recipe = models.ForeignKey(share_recipe, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'author_answer')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name = 'voter_answer')


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank = True)
    recipe = models.ForeignKey(share_recipe, null = True, blank = True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null = True, blank = True, on_delete = models.CASCADE)


class Photo(models.Model):
    recipe = models.ForeignKey(share_recipe, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

Django_Project/food/main_recipe/views/recipe_list_views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from ..models import main_recipe


def korean(request):
    page = request.GET.get('page', '1')
    korean_main_recipe = main_recipe.objects.filter(menu__contains='한식')
    paginator = Paginator(korean_main_recipe, 5)
    page_obj = paginator.get_page(page)
    context = {'recipe_list': page_obj}
    return render(request, 'main/korean_recipe_list.html', context)


def chinese(request):
    page = request.GET.get('page', '1')
    chinese_main_recipe = main_recipe.objects.filter(menu__contains='중식')
    paginator = Paginator(chinese_main_recipe, 5)
    page_obj = paginator.get_page(page)
    context = {'recipe_list': page_obj}
    return render(request, 'main/chinese_recipe_list.html', context)


def western(request):
    page = request.GET.get('page', '1')
    western_main_recipe = main_recipe.objects.filter(menu__contains='양식')
    paginator = Paginator(western_main_recipe, 5)
    page_obj = paginator.get_page(page)
    context = {'recipe_list': page_obj}
    return render(request, 'main/western_recipe_list.html', context)


def japanese(request):
    page = request.GET.get('page', '1')
    japanese_main_recipe = main_recipe.objects.filter(menu__contains='일식')
    paginator = Paginator(japanese_main_recipe, 5)
    page_obj = paginator.get_page(page)
    context = {'recipe_list': page_obj}
    return render(request, 'main/japanese_recipe_list.html', context)

Django_Project/food/main_recipe/views/recipe_views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from ..models import main_recipe, Photo
from ..forms import RecipeForm


@login_required(login_url = "common:login")
def recipe_create(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.create_date = timezone.now()
            recipe.save()
            for img in request.FILES.getlist('imgs'):
                photo = Photo()
                photo.recipe = recipe
                photo.image = img
                photo.save()

            if recipe.menu == "한식":
                return redirect('main:korean')
            elif recipe.menu == "중식":
                return redirect('main:chinese')
            elif recipe.menu == "일식":
                return redirect('main:japanese')
            else:
                return redirect('main:western')
    else:
        form = RecipeForm()
    context = {'form' : form}
    return render(request, 'main/recipe_form.html', context)


@login_required(login_url = "common:login")
def recipe_modify(request, recipe_id):
    recipe = get_object_or_404(main_recipe, pk=recipe_id)
    if request.user != recipe.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('main:recipe_detail', recipe_id = recipe.id)

    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.modify_date = timezone.now()
            recipe.save()
            for img in request.FILES.getlist('imgs'):
                photo = Photo()
                photo.recipe = recipe
                photo.image = img
                photo.save()
            return redirect('main:recipe_detail', recipe_id = recipe.id)
    else:
        form = RecipeForm(instance=recipe)
    context = {'form': form}
    return render(request, 'main/recipe_form.html', context)


@login_required(login_url = "common:login")
def recipe_delete(request, recipe_id):
    recipe = get_object_or_404(main_recipe, pk=recipe_id)
    if request.user != recipe.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('main:recipe_detail', recipe_id = recipe.id)
    recipe.delete()
    return redirect('main:index')

Django_Project/food/share_recipe/views/answer_views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import AnswerForm
from ..models import share_recipe, Answer


@login_required(login_url = "common:login")
def answer_create(request, recipe_id):
    recipe = get_object_or_404(share_recipe, pk = recipe_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.recipe = recipe
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('share:recipe_detail', recipe_id = recipe.id), answer.id))
    else:
        form = AnswerForm()
    context = {'recipe' : recipe, 'form' : form}
    return render(request, 'share/recipe_detail.html', context)


@login_required(login_url = "common:login")
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('share:recipe_detail', recipe_id = answer.recipe.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('share:recipe_detail', recipe_id = answer.recipe.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer' : answer, 'form': form}
    return render(request, 'share/answer_form.html', context)


@login_required(login_url = "common:login")
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다')
    else:
        answer.delete()
    return redirect('share:recipe_detail', recipe_id = answer.recipe.id)

Django_Project/food/share_recipe/views/comment_views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import CommentForm
from ..models import share_recipe, Answer, Comment

@login_required(login_url = "common:login")
def comment_create_recipe(request, recipe_id):
    recipe = get_object_or_404(share_recipe, pk = recipe_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.recipe = recipe
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('share:recipe_detail', recipe_id = comment.recipe.id), comment.id))
    else:
        form = CommentForm()
    context = {'form' : form}
    return render(request, 'share/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_recipe(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('share:recipe_detail', recipe_id=comment.recipe.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('share:recipe_detail', recipe_id=comment.recipe.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'share/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_recipe(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('share:recipe_detail', recipe_id=comment.recipe.id)
    else:
        comment.delete()
    return redirect('share:recipe_detail', recipe_id=comment.recipe.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('share:recipe_detail', recipe_id=comment.answer.recipe.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'share/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('share:recipe_detail', recipe_id=comment.answer.recipe.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('share:recipe_detail', recipe_id=comment.recipe.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'share/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('share:recipe_detail', recipe_id=comment.answer.recipe.id)
    else:
        comment.delete()
    return redirect('share:recipe_detail', recipe_id=comment.answer.recipe.id)

Django_Project/food/templates/share/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class = "container my-3">
    <form method = "post" class = "post-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class = "form-group">
            <label for = "content">답변 내용</label>
            <textarea class = "form-control" name = "content" id = "content" rows = "10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type = "submit" class = "btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

Django_Project/food/templates/share/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

Django_Project/food/templates/share/main.html
{% extends 'base.html' %}
{%load static %}
{% block content %}
<!--로고-->
<div id="inback">
    <div id="main-in">
        <h2 style="font-size:35pt;"><b>나만의 레시피를 만들어 뽑낼 수 있는 게시판입니다.</b></h2>
    </div>
<div id="inlogo">
        <img src="https://postfiles.pstatic.net/MjAyMTA1MjRfMTIy/MDAxNjIxODQxNzAyNzEz.sw9sfN3XrDFQHtyj3MUqDTx9qkazwoMCM-KuASIBPxgg.Aau2GOTPkBXbKE8df2fVzuEbu29utUVHgFctyzf97e4g.PNG.mmy0509/logo_transparent.png?type=w773"
        style="margin:0 auto; width:300px;">
        <link rel="stylesheet" href="{%static 'style.css'%}?a">
</div>
    <div id="centerfont">
        <img src="https://postfiles.pstatic.net/MjAyMTA1MzFfMTcx/MDAxNjIyMzkyODE5NjU2.cMAuWeAfugBuZKZuH7G1DAQp9IO-gu6gHBxW1FbYb7Ug.IEcW3ElwDoA20j-s_Arsv7sGNRMn7-SEkExpvSZ2nqwg.PNG.mmy0509/share.PNG?type=w773">
    </div>
    <!-- 한식 이동 -->
    <div id="s-korean">
        <a href="{% url 'share:korean' %}">✔한식</a><br>
        <a href="{% url 'share:korean' %}">우리나라 전통의 한식의 조리법을  공유하는 게시판 입니다.</a>
    </div>

    <!-- 중식 이동 -->
    <div id="chinese">
        <a href="{% url 'share:chinese' %}"title="중국 음식을 위한 레시피 게시판 입니다.">✔중식</a><br>
        <a href="{% url 'share:chinese' %}">중국의 조리법을 공유하는 게시판 입니다.</a>
    </div>

    <!-- 양식 이동 -->
    <div id="western">
        <a href="{% url 'share:western' %}"title="서양 음식을 위한 레시피 게시판 입니다">✔양식</a><br>
        <a href="{% url 'share:western' %}">서양의 음식 즉 양식의 조리법을 공유하는 게시판 입니다.  </a>
    </div>

    <!-- 일식 이동 -->
    <div id="japanese">
        <a href="{% url 'share:japanese' %}"title="일본 음식을 위한 레시피 게시판 입니다">✔일식</a><br>
        <a href="{% url 'share:japanese' %}"> 일본의 음식 조리법을 공유하는 게시판 입니다.</a>
    </div>
    <div id="share_button">
        <a href = "{% url 'share:recipe_create' %}" class = "btn btn-primary">레시피 등록하기</a>
    </div>
</div>
{% endblock %}

Django_Project/food/templates/share/recipe_detail.html
{% extends 'base.html' %}
{% load share_filter %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class = "alert alert-danger my-3" role = "alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">공유 레시피</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ recipe.voter.count }}</div>
            <a href="#" data-uri="{% url 'share:vote_recipe' recipe.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div><!-- 추천영역 end -->
        {% for photo in recipe.photo_set.all %}
            <img style="margin:0 auto;" src="{{photo.image.url}}"><br>
        {% endfor %}
        <div class = "col-11"><!-- 질문 영영 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ recipe.subject|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if recipe.modify_date %}
                        <div class = "badge badge-light p-2 text-left mx-3">
                            <div class = "mb-2">수정 일자</div>
                            <div>{{ recipe.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class = "mb-2">{{ recipe.author.username }}</div>
                            <div>{{ recipe.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == recipe.author %}
                    <div class = "my-3">
                        <a href = "{% url 'share:recipe_modify' recipe.id %}" class = "btn btn-sm btn-outline-secondary">수정</a>
                        <a href = "#" class = "delete btn btn-sm btn-outline-secondary" data-uri = "{% url 'share:recipe_delete' recipe.id %}">삭제</a>
                    </div>
                    {% endif %}
                    <!-- 질문 댓글 Start -->
                    {% if recipe.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in recipe.comment_set.all %}
                        <a name = "comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'share:comment_modify_recipe' comment.id  %}" class="small">수정</a>
                            <a href="#" class="small delete" data-uri="{% url 'share:comment_delete_recipe' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'share:comment_create_recipe' recipe.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">종류 : {{ recipe.menu }}</div>
                </div>
            </div>
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: nowrap;">주재료 : {{ recipe.material|mark }}</div>
                </div>
            </div>
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: nowrap;">만드는 법 : {{ recipe.how_Make|mark }}</div>
                </div>
            </div>
        </div>
    </div>

    <h5 class="border-bottom my-3 py-2">{{ recipe.answer_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in recipe.answer_set.all %}
    <a name = "answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ answer.voter.count }}</div>
            <a href="#" data-uri="{% url 'share:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">  <!-- 답변영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if recipe.modify_date %}
                        <div class = "badge badge-light p-2 text-left mx-3">
                            <div class = "mb-2">수정 일자</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class = "mb-2">{{ recipe.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                            {% if request.user == answer.author %}
                            <div class = "my-3">
                                <a href = "{% url 'share:answer_modify' answer.id %}" class = "btn btn-sm btn-outline-secondary">수정</a>
                                <a href = "#" class = "delete btn btn-sm btn-outline-secondary" data-uri = "{% url 'share:answer_delete' answer.id %}">삭제</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    {% if answer.comment_set.count > 0 %}
                        <div class="mt-3">
                        {% for comment in answer.comment_set.all %}
                            <a name = "comment_{{ comment.id }}"></a>
                            <div class="comment py-2 text-muted">
                                <span style="white-space: pre-line;">{{ comment.content|mark }}</span>
                                <span>
                                    - {{ comment.author }}, {{ comment.create_date }}
                                    {% if comment.modify_date %}
                                    (수정:{{ comment.modify_date }})
                                    {% endif %}
                                </span>
                                {% if request.user == comment.author %}
                                <a href="{% url 'share:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                                <a href="#" class="small delete"
                                   data-uri="{% url 'share:comment_delete_answer' comment.id  %}">삭제</a>
                                {% endif %}
                            </div>
                        {% endfor %}
                        </div>
                        {% endif %}
                        <div>
                            <a href="{% url 'share:comment_create_answer' answer.id  %}"
                               class="small"><small>댓글 추가 ..</small></a>
                        </div>
                        <!-- 질문 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'share:answer_create' recipe.id %}" method="post" class="my-3">
        {% csrf_token %}
<!-- 오류표시 Start-->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea name="content" id="content" {% if not user.is_authenticated %}disabled{% endif %} class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

{% block script %}
<script type = 'text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
        $(".recommend").on('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}