Django_Project/food/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup/', views.signup, name = 'signup'),
]

Django_Project/food/config/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main_recipe/', include('main_recipe.urls')),
    path('share_recipe/', include('share_recipe.urls')),
    path('best_recipe/', include('food.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('', views.mainpage, name = 'main'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django_Project/food/food/urls.py
from django.contrib import admin
from django.urls import path
from share_recipe.views import recipe_list_views

app_name = 'best'

urlpatterns = [
    path('', recipe_list_views.best_recipe_list, name = 'index'),
]

Django_Project/food/main_recipe/urls.py
from django.contrib import admin
from django.urls import path
from .views import base_views, recipe_list_views, recipe_views


app_name = 'main'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('korean/', recipe_list_views.korean, name = 'korean'),
    path('chinese/', recipe_list_views.chinese, name = 'chinese'),
    path('western/', recipe_list_views.western, name = 'western'),
    path('japanese/', recipe_list_views.japanese, name = 'japanese'),
    path('<int:recipe_id>/', base_views.recipe_detail, name = 'recipe_detail'),
    path('recipe/create/', recipe_views.recipe_create, name='recipe_create'),
    path('recipe/modify/<int:recipe_id>/', recipe_views.recipe_modify, name = 'recipe_modify'),
    path('recipe/delete/<int:recipe_id>/', recipe_views.recipe_delete, name = 'recipe_delete'),
]

Django_Project/food/share_recipe/urls.py
from django.urls import path
from .views import answer_views, base_views, comment_views, recipe_list_views, recipe_views, voter_views

app_name = 'share'

urlpatterns = [
    path('', base_views.index, name = 'index'),
    path('korean/', recipe_list_views.korean, name = 'korean'),
    path('chinese/', recipe_list_views.chinese, name = 'chinese'),
    path('western/', recipe_list_views.western, name = 'western'),
    path('japanese/', recipe_list_views.japanese, name = 'japanese'),
    path('<int:recipe_id>/', base_views.recipe_detail, name = 'recipe_detail'),
    path('answer/create/<int:recipe_id>/', answer_views.answer_create, name = 'answer_create'),
    path('recipe/create/', recipe_views.recipe_create, name = 'recipe_create'),
    path('recipe/modify/<int:recipe_id>/', recipe_views.recipe_modify, name = 'recipe_modify'),
    path('recipe/delete/<int:recipe_id>/', recipe_views.recipe_delete, name = 'recipe_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name = 'answer_delete'),
    path('comment/create/recipe/<int:recipe_id>/', comment_views.comment_create_recipe, name = 'comment_create_recipe'),
    path('comment/modify/recipe/<int:comment_id>/', comment_views.comment_modify_recipe, name = 'comment_modify_recipe'),
    path('comment/delete/recipe/<int:comment_id>/', comment_views.comment_delete_recipe, name = 'comment_delete_recipe'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:recipe_id>/', voter_views.vote_recipe, name='vote_recipe'),
    path('vote/answer/<int:answer_id>/', voter_views.vote_answer, name='vote_answer'),
]

Django_Project/food/main_recipe/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import main_recipe, Photo


def index(request):
    return render(request, 'main/main.html')


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(main_recipe, pk = recipe_id)
    context = {'recipe' : recipe}
    return render(request, 'main/recipe_detail.html', context)

Django_Project/food/share_recipe/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import share_recipe


def index(request):
    return render(request, 'share/main.html')


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(share_recipe, pk = recipe_id)
    context = {'recipe' : recipe}
    return render(request, 'share/recipe_detail.html', context)

Django_Project/food/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content = "width = device-width, initital-scale = 1, shrink-to-fit-no">
    <link rel = "stylesheet" type = "text/css" href = "{% static 'bootstrap.min.css' %}">
    <title>조별과제!!!!</title>
</head>

<body>
<!--네비게이션바 포함-->
{% include "navbar.html" %}
<!------------------>
<!-- 기본 템플릿 안에 삽입될 내용 START -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 END -->

<script src = "{%static 'jquery-3.6.0.min.js' %}"></script>
<script src = "{%static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

Django_Project/food/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

Django_Project/food/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'main' %}"style="margin-left:3rem;"><b>레시피 홈페이지</b></a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div id="nav-recipe">
        <a class="navbar-brand" href="{% url 'main:index' %}">메인 레시피</a>
        <a class="navbar-brand" href="{% url 'share:index' %}">공유 레시피</a>
        <a class="navbar-brand" href="{% url 'best:index' %}">추천 레시피</a>
         </div>
    <!-- 로그인 구역-->
        <div style="display:block; padding-right: 0; margin-right:3rem; float:right;"class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class = "nav-link" href = "{% url 'common:logout' %}?next={{ request.path }}">
                            {{ user.username }} (로그아웃)
                        </a>
                    <link rel="stylesheet" href="{%static 'style.css'%}?a">
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}?next={{ request.path }}">로그인</a>
                        <link rel="stylesheet" href="{%static 'style.css'%}?a">
                    {% endif %}
                </li>
            </ul>
        </div>
</nav>